### ISSUE TITLE
Chimoney Hacktoberfest Contribution

### ISSUE THREAD

**Issue by phyleria** [mzoyinda/Chimoney-Redeem-Airtime#3]
Hi there @mzoyinda 
Kindly provide your email address to be able to receive your reward as a HacktoberFest Contributor for the Chimoney Community Projects. Thank you!

**Comment by mzoyinda** [comment]
Yaaayyyhhhh...🥳.🤩 

oyindamoladawodu22@gmail.com

Thank you.

**Comment by phyleria** [comment]
Thank you @mzoyinda !
